# Generated by Django 5.0 on 2023-12-17 12:03

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("animal", models.CharField(max_length=255)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "log",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(
                            blank=True,
                            default=dict,
                            help_text="update details for the case",
                            null=True,
                        ),
                        blank=True,
                        default=list,
                        help_text="a list of updates for the case",
                        size=None,
                    ),
                ),
            ],
        ),
    ]
