# Generated by Django 5.0 on 2023-12-27 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
