# Generated by Django 5.0 on 2024-01-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_case_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="consent",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="verify_key",
        ),
        migrations.AddField(
            model_name="user",
            name="home_address",
            field=models.TextField(
                default="15 West Pennant Road, Sambro, Nova Scotia, B3R 2C6"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="mobile_phone",
            field=models.CharField(default="9024302488", max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="travel_distance",
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
