# Generated by Django 5.0 on 2024-01-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_remove_user_consent_remove_user_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="home_coordinates",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
