# Generated by Django 5.0 on 2024-01-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_user_home_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="messages_sent",
            field=models.IntegerField(default=0, help_text="Number of messages sent"),
        ),
    ]
