# Generated by Django 5.0 on 2024-01-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_case_messages_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="logged_in",
            field=models.BooleanField(default=False),
        ),
    ]
