# Generated by Django 5.0 on 2024-02-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_user_logged_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.CharField(
                default="Dispatch (including triage centers)", max_length=255
            ),
            preserve_default=False,
        ),
    ]
