relay_points = {'Relay Point Westchester': '3395-3399 Wentworth Collingwood Road Westchester Station  NS B0M 2A0',
 'Relay Point Truro. Robie Street': '7 Robie Street Truro  NS B2N 1K8',
 'Relay Point Truro Millbrook Exit': '20 Treaty Trail Millbrook  NS B6L 1W2',
 'Relay Point Truro Heights': '86 Truro Heights Connector Truro Heights  NS B6L 1P3',
 'Relay Point Tracadie (Pomquet And Afton)': 'Mary Browns Pomquet And Afton NS',
 'Relay Point Tantallon': '3664 Route 213 Upper Tantallon  NS B3Z 4R2',
 'Relay Point Stewiake': '89 Main Street West Stewiake NS B0N 2J0',
 'Relay Point St Peters': '10041 Greenville St St Peters NS B0E 3B0',
 'Relay Point Shelburne': '90 Route 203 Shelburne NS',
 'Relay Point Salt Springs': '1120 Pleasent Valley Road Westville  NS B0K 2A0',
 'Relay Point Oxford': '4602 Main Street  Oxford NS B0M 1P0',
 'Relay Point New Glasgow': '5197 East River Road New Glasgow  NS B2H 5C5',
 'Relay Point Milford': '55 Trunk 14 Milford  NS B0N 1Y0',
 'Relay Point Middleton': '1036 Brooklyn Street Middleton NS B0S 1P0',
 'Relay Point Masstown': '10635 Trunk 2 Debert NS B0M 1G0',
 'Relay Point Liverpool': '57 Old Falls Road Liverpool  NS B0T1B0',
 'Relay Point Kemptown': 'Mount Thom Conn Colchester  NS',
 'Relay Point Irish Cove': '16165 Highway 4 Irish Cove NS B0E 1M0',
 'Relay Point Halifax': '3601 Joseph Howe Drive Halifax  NS B3L 4H8',
 'Relay Point Forrest Hills Dartmouth': '612 Main Street  Dartmouth  NS B2W 5M5',
 'Relay Point Fall River': '2946 Trunk2 Fall River NS B2T 1J5',
 'Relay Point Enfield': '6742 Trunk 2 Enfield  NS B2T 1C1',
 'Relay Point Elmsdale': '291 Route 214 Elmsdale  NS B2S 2L1',
 'Relay Point Digby': '492 Route 303 Digby NS B0N 1A0',
 'Relay Point Debert': '439 MacElmon Road Debert NS B0M 1G0',
 'Relay Point Dartmouth (Highfield Park)': '14 Highfield Park Drive Dartmouth  NS B3A 4T6',
 'Relay Point Dartmouth Crossing': '145 Shubie Drive Dartmouth Crossing  NS B3B 0C3',
 'Relay Point Concession': '831 Little Brook Road Concession  NS B0W 1M0',
 'Relay Point Bridgewater': '2760 Route 325 Wileville  NS B4V 5G2',
 'Relay Point Bible Hill': '620 Pictou Road Valley  NS B2N 2V1',
 'Relay Point Berwick': '300 Commercial Street Berwick NS B0P 1E0',
 'Relay Point Bedford': '1772 Bedford Highway  Bedford   B4A 3X5',
 'Relay Point Barrington': 'Oak Park Connector  Barrington  NS',
 'Relay Point Baddeck': '8250 Trans Canada Highway 105 Baddeck NS B0E 1B0',
 'Relay Point Aulds Cove (Causeway)': '13239 Trans Canada Highway 104 Harve Boucher  NS B0H 1P0',
 'Relay Point Antigonish': '5723 Trunk7 Antigonish  NS B2 G 2J5'}